### ISSUE TITLE
自定义布局中设置问题

### ISSUE THREAD

**Issue by mayi8986** [yilylong/CBDialog#10]
自定义布局中设置.showCancelButton(true)不起作用
只显示ConfirmButton
而且监听也不起作用，下载demo修改如下也是不行
`         case R.id.custom_dialog_layout:
                new CBDialogBuilder(this, R.layout.layout_custom_dialog_layout, 1.0f)
                        .setTouchOutSideCancelable(true)
                        .showCancelButton(true)
                        .setCancelButtonText("取消")
                        .setDialoglocation(CBDialogBuilder.DIALOG_LOCATION_BOTTOM)
                        .setTitle("这是一个自定义dialog布局样式的对话框")
                        .setMessage("去除了dialog的圆角背景")
                        .setConfirmButtonText("确定")
                        .setDialogAnimation(CBDialogBuilder.DIALOG_ANIM_SLID_BOTTOM)
                        .setButtonClickListener(true, new CBDialogBuilder.onDialogbtnClickListener() {
                            @Override
                            public void onDialogbtnClick(Context context, Dialog dialog, int whichBtn) {
                                Toast.makeText(context, "点击了确定", Toast.LENGTH_SHORT).show();
                            }
                        })
                        .create().show();

                break;`

**Comment by yilylong** [comment]
因为在自定义的布局layout_custom_dialog_layout.xml中我去掉了取消按钮 只有确认按钮`<LinearLayout
        android:id="@+id/dialog_btnlayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="10dp"
        android:orientation="horizontal" >

        <Button
            android:id="@+id/dialog_posi_btn"
            style="@style/dialog_button_style"
            android:background="@drawable/custom_btn_bg"
            android:text="确定" />
    </LinearLayout>`

你想要有取消按钮在你自定义的布局中加入取消按钮即可，view的id参考cb_dialog.xml 中的即可（id要一样不然找不到这个按钮）。
`<LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <Button
                android:id="@+id/dialog_neg_btn"
                style="@style/dialog_button_style"
                android:background="@drawable/cb_button_background_left"
                android:text="取消"
                android:textColor="@color/cb_btn_bg_blue"
                android:visibility="gone" />

            <View
                android:id="@+id/btn_line_verticle"
                android:layout_width="0.5dp"
                android:layout_height="match_parent"
                android:background="@color/btn_bg_line"
                android:visibility="gone" />

            <Button
                android:id="@+id/dialog_posi_btn"
                style="@style/dialog_button_style"
                android:background="@drawable/cb_button_background_right"
                android:text="确定"
                android:textColor="@color/cb_btn_bg_blue" />

        </LinearLayout>`

**Comment by mayi8986** [comment]
我在自定义布局中加入了取消按钮 ，id也是一样的，确定按钮的监听事件都获取不到

**Comment by yilylong** [comment]
测试了下确实有问题，已经修改，可以更新到最新v1.0.7
