### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by shuyuTech** [yilylong/CBDialog#2]
**当Dialog被创建之后在别的地方无法更新他的内容。**
_当他是一个要接收持续状态的Dialog的时候尤为重要_
暂时的解决方案：如下先找到控件
` TextView dialogMsg = (TextView) dialog.findViewById(com.zhl.cbdialog.R.id.dialog_message);//eg`
` Button  confrimBtn = (Button) dialog.findViewById(com.zhl.cbdialog.R.id.dialog_posi_btn);//eg`
//重新设置值
`  dialogMsg.setText("正在获取服务器数据库更新..."); //eg`
`  dialogMsg.setText("正在解析..."); //eg`
但是我不认为这是一个好的解决方案，如果作者有时间精力，希望能提供解决方案(例如：不使用Dialog作为返回值，而是CBDialog)
期待您的回复：）

**Comment by yilylong** [comment]
有个setView方法 可以自己加载自定义view就可以解决你说的问题了


发自网易邮箱 iPhone 版
在2016年12月06日 14:49，刘 写道:

当Dialog被创建之后在别的地方无法更新他的内容。
当他是一个要接收持续状态的Dialog的时候尤为重要
暂时的解决方案：如下先找到控件
TextView dialogMsg = (TextView) dialog.findViewById(com.zhl.cbdialog.R.id.dialog_message);//eg
Button confrimBtn = (Button) dialog.findViewById(com.zhl.cbdialog.R.id.dialog_posi_btn);//eg
//重新设置值
dialogMsg.setText("正在获取服务器数据库更新..."); //eg
dialogMsg.setText("正在解析..."); //eg
但是我不认为这是一个好的解决方案，如果作者有时间精力，希望能提供解决方案(例如：不使用Dialog作为返回值，而是CBDialog)
期待您的回复：）
