### ISSUE TITLE
显示不出

### ISSUE THREAD

**Issue by 2shiwenbin0522** [yilylong/CBDialog#5]
您好 我想问一下 为什么有些手机上显示不出对话框来?

**Comment by 2shiwenbin0522** [comment]
比如说是在vivo x7就显示不出来

**Comment by yilylong** [comment]
等我借个手机来测试下

**Comment by yilylong** [comment]
vivo X7 亲测没有任何问题，都是系统API应都支持的。你看看是不是手机上的权限系统设置了什么还是其他问题。
