### ISSUE TITLE
请教关于Dialog的关于FragmentDialog

### ISSUE THREAD

**Issue by ysmintor** [yilylong/CBDialog#6]
[官方Dialog Guide](https://developer.android.com/guide/topics/ui/dialogs.html)都是直接从`FragmentDialog`,` [可以保存dialog的数据，生命周期便于管理。而这个库直接使用Dialog来管理，有考虑前面的问题吗？

**Comment by yilylong** [comment]
没有，可以建一个工具类来统一管理dialog的创建或显示。
